refactor: pinned crypto deps to github tags
matter-labs/era-zk_evm pull request #19
Opened 2023-10-09 17:35 UTC by pompon0

## What

This PR replaces version pinning with github tag pinning which excludes these particular dependencies from dependency resolver analysis, therefore allowing upstream crates to depend on the newer version as well.

## Why

Cargo doesn't allow to depend on multiple semver-compatible versions of a single crate. Since this crate binds crypto libraries to 0.10.6 it is not possible to depend on newer versions upstream.

2023-10-10 10:55 UTC, shamatar commented
Then k256 should also be pinned same way. Hashes crates were set to particular versions due to some internal breaking changes they had, but let's do all in a same way then

2023-10-10 10:57 UTC, shamatar requested changes
Just remove those completely and import and re-export from opcode-defs

2023-10-10 11:01 UTC, shamatar commented
Another question is why is it into so old branch?

2023-10-11 11:43 UTC, pompon0 commented
era-zksync depends on these branches as it uses old VMs to execute old blocks. The new branches do not have the dependencies pinned (or at least I haven't found the pinnings which would block upgrades).

2023-10-11 11:57 UTC, pompon0 commented
opcode-defs on branch v1.3.1 (which this branch depends on) imports only sha2 at "0.10" (not pinned) and doesn't export it at all.

2023-10-11 12:37 UTC, shamatar commented
If as you said k256 doesn't affect you then it's ok

2023-10-11 12:37 UTC, shamatar submitted a review, later dismissed

2023-10-11 15:30 UTC, MexicanAce commented
Please create a `TODO` and use commit hash instead of tags if we must use `git` dependencies.

Per development standards/guidelines:

> With external dependencies, always try to avoid using git dependencies. If you are forced to use git dependency (e.g. to get access to an unreleased fix in a third-party library), prefer using commit hashes, since tags may not be immutable there. In such cases, add a TODO and create a task to get rid of the git dependency as soon as possible.

2023-10-13 13:42 UTC, shamatar approved these changes

2023-10-13 14:43 UTC, merged